CREATE DATABASE TODOAPPDB;
GO
USE TODOAPPDB;
GO
CREATE TABLE Todo (
	ID INT PRIMARY KEY IDENTITY(1,1),
	TASK NVARCHAR(MAX),
	DONE BIT DEFAULT 0,
	CREATEDDATE DATETIME DEFAULT CURRENT_TIMESTAMP,
	UPDATEDDATE DATETIME NULL
);